name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
      
    - name: Setup Java Action
      uses: actions/setup-java@v1.0.0
      with:
        # The JDK version to make available on the path. Takes a whole or semver Jdk version, or 1.x syntax (e.g. 1.8 => Jdk 8.x)
        version: 1.8
        # The architecture (x86, x64) of the JDK.
        architecture: x64
        
       
